FROM python:3.8.1

WORKDIR /Machine-Learning-Projects/Microservice
COPY . /Machine-Learning-Projects/Microservice

RUN pip install -r requirements.txt

EXPOSE 5000/tcp
EXPOSE 5000/udp

CMD ["python3", "Machine-Learning-Projects/Microservice/house_price.py","-p","Machine-Learning-Projects/Microservice/model.pickle"]
