FROM python:3.6-slim

ENV APP_HOME /app
WORKDIR $APP_HOME
COPY . /app

RUN pip install -r requirements.txt

EXPOSE 5000

CMD ["python", "./house_price.py","-p","Machine-Learning-Projects/Microservice/model.pickle"]
