# This is a basic workflow to help you get started with Actions

name: deploy-heroku

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "microservice-heroku" #Must be unique in Heroku
          heroku_email: "mohammad.khamlan@stu.najah.edu"
          usedocker: 1
          dontuseforce: 1
