# This is a basic workflow to help you get started with Actions

name: dockerhub

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: docker_run
        env: 
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          
      - name: docker_build
        run: |
          docker build "./Microservice" -t ${{secrets.DOCKER_USERNAME}}/microservice:latest
      # Runs a set of commands using the runners shell
      - name: docker_push
        run: |
          docker push ${{secrets.DOCKER_USERNAME}}/microservice:latest

      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "microservice-heroku"
          heroku_email: "mohammad.khamlan@stu.najah.edu"
          usedocker: 1
          dontuseforce: 1

