name: Deploy-heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "microservice-heroku" 
          heroku_email: "mohammad.khamlan@stu.najah.edu"
      - name: Add remote origin
        run: |
           git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/microservice-heroku.git
      - name: Deploy to Heroku
        run: |
           git push origin master --force
