name: Deploy-heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  
          heroku_app_name: "microservice-heroku" 
          heroku_email: "mohammad.khamlan@stu.najah.edu"
        env: 
         run: heroku container:login 
      - name: Build and push
        env:
         run: heroku container:push -a microservice-heroku web 
      - name: Release
        env:
         run: heroku container:release -a microservice-heroku web   
